name: team-syncer

inputs:
  CONFIG_REPO:
    description: 'Central repository containing the configuration file'
    required: false
    default: 'common'
  CONFIG_FILE:
    description: 'Path to the configuration file in the central repository'
    required: false
    default: 'teams_config.yaml'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN to be stored as a secret'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      env:
        YQ_VERSION: v4.44.2
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl wget tar
        wget --no-verbose https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64.tar.gz -O - |\
          tar xz && mv yq_linux_amd64 /usr/local/bin/yq && chmod +x /usr/local/bin/yq

    - name: Sync teams to repository
      shell: bash
      run: |
        set -e

        GITHUB_ORG=${{ github.repository_owner }}
        GITHUB_REPO=${{ github.event.repository.name }}
 
        CONFIG_REPO="${GITHUB_ORG}/common"
        CONFIG_FILE="${{ inputs.CONFIG_FILE }}"
        
        SUPPORTED_PERMISSIONS=("pull" "push" "admin" "maintain" "triage")
        
        fetch_config() {
          curl -s -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
            -L "https://raw.githubusercontent.com/${CONFIG_REPO}/main/${CONFIG_FILE}" \
            -o $CONFIG_FILE
        }
        
        # Function to sync teams to a repository
        sync_teams_to_repo() {
          local team=$1
          local permission=$2
        
          # Validate permission
          local valid_permission=false
          for p in "${SUPPORTED_PERMISSIONS[@]}"; do
            if [[ "$p" == "$permission" ]]; then
              valid_permission=true
              break
            fi
          done
        
          if [[ "$valid_permission" == false ]]; then
            echo "Invalid permission: $permission for team: $team. Skipping..."
            return
          fi
        
          curl -s -X PUT -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/$GITHUB_ORG/teams/$team/repos/$GITHUB_ORG/$GITHUB_REPO" \
            -d "{\"permission\":\"$permission\"}"
        }
        
        # Sync the teams to the repository.
        fetch_config
        teams=$(yq e '.teams' -o=json "$CONFIG_FILE")

        # Check if teams is empty
        if [ -z "$teams" ]; then
          echo "No teams defined in $CONFIG_FILE"
          exit 1
        fi
        
        echo "$teams" | jq -c '.[]' | while read -r team; do
          team_name=$(echo "$team" | jq -r '.name')
          team_permission=$(echo "$team" | jq -r '.permission')
        
          echo "Syncing team: $team_name with permission: $team_permission to repository $GITHUB_ORG/$GITHUB_REPO"
          
          sync_teams_to_repo $team_name $team_permission
        done
