# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner to use for the job"
        required: false
        default: "default"
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs-on}}
    steps:
    - name: Print Inputs
      run: |
        echo "====${{ github.workflow }} Inputs===="
        echo "Inputs: ${{ toJson(inputs) }}"
        echo "===="

    - uses: actions/checkout@v4

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
