name: REUSE Compliance Check

on: [pull_request]

jobs:
  test:
    runs-on: [ default ]
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: ./workflows/ci-reuse-check.yaml
      