name: REUSE Compliance Check

on: [pull_request]

jobs:
  test:
    runs-on: [ default ]
    steps:
    - name: REUSE Compliance Check
      uses: cloudoperators/common/workflows/ci-reuse-check.yaml@main
