name: Shared Check & Fix License Header

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner to use for the job"
        required: false
        default: "ubuntu-latest"
        type: string
      apply_header:
        description: "Apply automatically license header"
        required: false
        default: true
        type: boolean
    secrets:
      app_id:
        description: "GitHub App ID for token generation"
        required: false
      private_key:
        description: "GitHub App private key for token generation"
        required: false

jobs:
  build-license-eye:
    name: Build LicenseEye
    if: inputs.apply_header == false
    runs-on: ${{ inputs.runs-on}}
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check License Header
        uses: apache/skywalking-eyes/header@5c5b974209f0de5d905f37deb69369068ebfc15c # v0.7.0
        with:
            config: .github/licenserc.yaml
            mode: check

  apply-license-header:
    name: Apply LicenceHeader
    if: inputs.apply_header == true
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write

    steps:
    - name: Generate GitHub App Token
      id: github-app-token
      continue-on-error: true
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: ${{ secrets.app_id }}
        private-key: ${{ secrets.private_key }}
        permission-contents: write

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: ${{ steps.github-app-token.outputs.token || inputs.pas != '' && inputs.pas || secrets.GITHUB_TOKEN }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Check License Header
      uses: apache/skywalking-eyes/header@5c5b974209f0de5d905f37deb69369068ebfc15c # v0.7.0
      with:
          config: .github/licenserc.yaml
          mode: fix

    - name: Apply Changes
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
      with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
